type Config = struct {
  gas_to_delete_session: u64,
  minimum_session_duration_ms: u64,
  ms_per_block: u64,
};

type Comment = struct {
  id: u64,
  post_id: u64,
  parent_id: opt u64,
  author: actor_id,
  text: str,
  image_uri: opt str,
  created_at: u64,
  upvotes: u32,
  reply_count: u32,
};

type Post = struct {
  id: u64,
  author: actor_id,
  text: str,
  image_uri: opt str,
  created_at: u64,
  upvotes: u32,
  comment_count: u32,
};

type Profile = struct {
  wallet: actor_id,
  username: opt str,
  social_handle: opt str,
  description: opt str,
  avatar_uri: opt str,
  created_at: u64,
  total_posts: u32,
  total_vibes_earned: u64,
};

type SignatureData = struct {
  key: actor_id,
  duration: u64,
  allowed_actions: vec ActionsForSession,
};

type ActionsForSession = enum {
  CreatePost,
  ToggleUpvote,
  CreateComment,
  ToggleCommentUpvote,
  UpdateProfile,
};

type SessionData = struct {
  key: actor_id,
  expires: u64,
  allowed_actions: vec ActionsForSession,
  expires_at_block: u32,
};

constructor {
  New : (config: Config);
};

service MiniReddit {
  CreateComment : (post_id: u64, parent_id: opt u64, text: str, image_uri: opt str, session_for_account: opt actor_id) -> result (u64, str);
  CreatePost : (text: str, image_uri: opt str, session_for_account: opt actor_id) -> result (struct { u64, u64 }, str);
  ToggleCommentUpvote : (comment_id: u64, session_for_account: opt actor_id) -> result (struct { u32, bool }, str);
  ToggleUpvote : (post_id: u64, session_for_account: opt actor_id) -> result (struct { u32, bool }, str);
  UpdateProfile : (username: opt str, social_handle: opt str, description: opt str, avatar_uri: opt str, session_for_account: opt actor_id) -> result (null, str);
  query GetAllComments : () -> vec Comment;
  query GetAllPosts : () -> vec Post;
  query GetCommentsForPost : (post_id: u64) -> vec Comment;
  query GetProfile : (wallet: actor_id) -> opt Profile;
  query GetVibesBalance : (wallet: actor_id) -> u64;
};

service Session {
  CreateSession : (signature_data: SignatureData, signature: opt vec u8) -> null;
  DeleteSessionFromAccount : () -> null;
  DeleteSessionFromProgram : (session_for_account: actor_id) -> null;
  query SessionForTheAccount : (account: actor_id) -> opt SessionData;
  query Sessions : () -> vec struct { actor_id, SessionData };

  events {
    SessionCreated;
    SessionDeleted;
  }
};

